'use client';

import { useState } from 'react';
import styles from './NumerologyCompatibilityCalculator.module.scss';

type Props = { locale: string };

const T: Record<string, {
  label1: string; label2: string; btn: string;
  pathLabel: string; scoreLabel: string;
  errEmpty: string; errInvalid: string;
  levels: { excellent: string; good: string; moderate: string; challenging: string };
}> = {
  en: { label1: 'Date of birth — Person 1', label2: 'Date of birth — Person 2', btn: 'Calculate Compatibility', pathLabel: 'Life Path', scoreLabel: 'Compatibility Score', errEmpty: 'Please enter both dates of birth.', errInvalid: 'Please enter valid dates.', levels: { excellent: 'Excellent Match', good: 'Good Match', moderate: 'Moderate Match', challenging: 'Challenging Match' } },
  ru: { label1: 'Дата рождения — Человек 1', label2: 'Дата рождения — Человек 2', btn: 'Рассчитать совместимость', pathLabel: 'Жизненный путь', scoreLabel: 'Совместимость', errEmpty: 'Введите обе даты рождения.', errInvalid: 'Введите корректные даты.', levels: { excellent: 'Отличная совместимость', good: 'Хорошая совместимость', moderate: 'Умеренная совместимость', challenging: 'Сложная совместимость' } },
  uk: { label1: 'Дата народження — Особа 1', label2: 'Дата народження — Особа 2', btn: 'Розрахувати сумісність', pathLabel: 'Шлях життя', scoreLabel: 'Сумісність', errEmpty: 'Введіть обидві дати народження.', errInvalid: 'Введіть коректні дати.', levels: { excellent: 'Чудова сумісність', good: 'Хороша сумісність', moderate: 'Помірна сумісність', challenging: 'Складна сумісність' } },
  fr: { label1: 'Date de naissance — Personne 1', label2: 'Date de naissance — Personne 2', btn: 'Calculer la compatibilité', pathLabel: 'Chemin de Vie', scoreLabel: 'Score de compatibilité', errEmpty: 'Veuillez entrer les deux dates de naissance.', errInvalid: 'Veuillez entrer des dates valides.', levels: { excellent: 'Excellente compatibilité', good: 'Bonne compatibilité', moderate: 'Compatibilité modérée', challenging: 'Compatibilité difficile' } },
  lt: { label1: 'Gimimo data — Asmuo 1', label2: 'Gimimo data — Asmuo 2', btn: 'Apskaičiuoti suderinamumą', pathLabel: 'Gyvenimo kelias', scoreLabel: 'Suderinamumo balas', errEmpty: 'Įveskite abi gimimo datas.', errInvalid: 'Įveskite teisingas datas.', levels: { excellent: 'Puikus suderinamumas', good: 'Geras suderinamumas', moderate: 'Vidutinis suderinamumas', challenging: 'Sudėtingas suderinamumas' } },
};

type CompatEntry = { score: number; en: string; ru: string; uk: string; fr: string; lt: string };

const COMPAT: Record<string, CompatEntry> = {
  '1-1': { score: 72, en: 'Two 1s share fierce independence and ambition — they respect each other deeply but must consciously take turns leading.', ru: 'Два Единственных разделяют сильную независимость и амбиции — они глубоко уважают друг друга, но должны сознательно поочерёдно брать лидерство.', uk: 'Два Одиниці поділяють сильну незалежність і амбіції — вони глибоко поважають одне одного, але повинні свідомо чергувати лідерство.', fr: 'Deux 1 partagent une forte indépendance et de l\'ambition — ils se respectent profondément mais doivent alterner consciemment dans le leadership.', lt: 'Du 1 dalijasi stipria nepriklausomybe ir ambicijomis — jie giliai gerbia vienas kitą, bet turi sąmoningai paeiliui vadovauti.' },
  '1-2': { score: 68, en: 'The bold leader meets the sensitive peacemaker — complementary strengths if 1 learns to soften and 2 learns to assert.', ru: 'Смелый лидер встречает чуткого миротворца — взаимодополняющие сильные стороны, если 1 учится мягкости, а 2 — настойчивости.', uk: 'Сміливий лідер зустрічає чуйного миротворця — взаємодоповнюючі сили, якщо 1 навчається м\'якості, а 2 — наполегливості.', fr: 'Le leader audacieux rencontre le pacificateur sensible — des forces complémentaires si le 1 apprend la douceur et le 2 l\'affirmation.', lt: 'Drąsus lyderis susitinka jautrų taikdarį — papildančios stiprybės, jei 1 mokosi švelniasio, o 2 — ryžtingumo.' },
  '1-3': { score: 82, en: 'A naturally energising pair — the leader\'s drive fuels the creator\'s expression and together they inspire each other to reach new heights.', ru: 'Естественно воодушевляющая пара — стремление лидера питает самовыражение творца, и вместе они вдохновляют друг друга на новые высоты.', uk: 'Природно надихаюча пара — прагнення лідера живить самовираження творця, і разом вони надихають одне одного на нові висоти.', fr: 'Un duo naturellement stimulant — la motivation du 1 nourrit l\'expression créative du 3 et ensemble ils s\'élèvent vers de nouveaux sommets.', lt: 'Natūraliai energizuojanti pora — lyderio ryžtas maitina kūrėjo raišką ir kartu jie įkvepia vienas kitą siekti naujų aukštumų.' },
  '1-4': { score: 58, en: 'The fast-moving 1 and the methodical 4 can clash on pace and style, but with patience their shared determination builds something lasting.', ru: 'Стремительная 1 и методичная 4 могут конфликтовать по темпу и стилю, но при терпении их общая решимость создаёт что-то долговечное.', uk: 'Стрімка 1 і методична 4 можуть конфліктувати за темпом та стилем, але при терпінні їхня спільна рішучість створює щось довговічне.', fr: 'Le 1 rapide et le 4 méthodique peuvent se heurter sur le rythme, mais avec patience leur détermination commune construit quelque chose de durable.', lt: 'Greitas 1 ir metodiškas 4 gali konfliktuoti dėl tempo, bet su kantrybe jų bendras ryžtas sukuria kažką ilgalaikio.' },
  '1-5': { score: 75, en: 'Two free spirits who love excitement — dynamic and stimulating, though both need to commit to something bigger than individual freedom.', ru: 'Два свободных духа, любящих приключения — динамичный и стимулирующий союз, хотя обоим нужно посвятить себя чему-то большему, чем личная свобода.', uk: 'Два вільних духи, що люблять пригоди — динамічний і стимулюючий союз, хоча обом потрібно присвятити себе чомусь більшому, ніж особиста свобода.', fr: 'Deux esprits libres qui aiment l\'aventure — une union dynamique et stimulante, bien que les deux doivent s\'engager envers quelque chose de plus grand.', lt: 'Du laisvi dvasios žmonės, mėgstantys nuotykius — dinamiškas ir skatinantis ryšys, nors abiem reikia įsipareigoti kažkam didesniam nei asmeninė laisvė.' },
  '1-6': { score: 62, en: 'Independent 1 and nurturing 6 face a tug-of-war between freedom and commitment — deep respect can bridge this gap if both are willing.', ru: 'Независимая 1 и заботливая 6 сталкиваются с противостоянием свободы и обязательств — глубокое уважение может преодолеть этот разрыв, если оба готовы.', uk: 'Незалежна 1 і дбайлива 6 стикаються з протистоянням свободи та зобов\'язань — глибока повага може подолати цю прогалину, якщо обидва готові.', fr: 'Le 1 indépendant et le 6 protecteur font face à une tension entre liberté et engagement — le respect profond peut combler ce fossé.', lt: 'Nepriklausomas 1 ir rūpestingas 6 susiduria su laisvės ir įsipareigojimo įtampa — gili pagarba gali užpildyti šią spragą, jei abu pasiryžę.' },
  '1-7': { score: 72, en: 'Both value their independence and inner world — they form a quietly powerful bond built on mutual respect and intellectual depth.', ru: 'Оба ценят независимость и внутренний мир — они формируют тихо мощную связь, построенную на взаимном уважении и интеллектуальной глубине.', uk: 'Обоє цінують незалежність та внутрішній світ — вони утворюють тихо потужний зв\'язок, побудований на взаємній повазі та інтелектуальній глибині.', fr: 'Tous deux apprécient l\'indépendance et le monde intérieur — ils forment un lien puissant et discret fondé sur le respect mutuel et la profondeur intellectuelle.', lt: 'Abu vertina nepriklausomybę ir vidinį pasaulį — jie formuoja ramiai galingą ryšį, pagrįstą abipuse pagarba ir intelektiniu gyliu.' },
  '1-8': { score: 78, en: 'A true power couple — both driven, ambitious and capable of great achievement when their energy aligns rather than competes.', ru: 'Настоящая сильная пара — оба целеустремлённые, амбициозные и способны на великие достижения, когда их энергия согласована, а не конкурирует.', uk: 'Справжня сильна пара — обидва цілеспрямовані, амбітні та здатні на великі досягнення, коли їхня енергія узгоджена, а не конкурує.', fr: 'Un vrai couple de pouvoir — tous deux motivés et ambitieux, capables de grandes réalisations quand leur énergie est alignée plutôt que compétitive.', lt: 'Tikra galios pora — abu ryžtingi, ambicingi ir pajėgūs didelių pasiekimų, kai jų energija yra suderinta, o ne konkuruoja.' },
  '1-9': { score: 65, en: 'The self-focused 1 and the universally-minded 9 pull in different directions — growth comes when each learns from the other\'s perspective.', ru: 'Сосредоточенная на себе 1 и ориентированная на мир 9 тянут в разные стороны — рост приходит, когда каждый учится на перспективе другого.', uk: 'Зосереджена на собі 1 і орієнтована на світ 9 тягнуть у різні боки — зростання приходить, коли кожен навчається з перспективи іншого.', fr: 'Le 1 centré sur lui-même et le 9 tourné vers l\'universel tirent dans des directions différentes — la croissance vient quand chacun apprend de l\'autre.', lt: 'Į save orientuotas 1 ir į universumą orientuotas 9 traukia skirtingomis kryptimis — augimas ateina, kai kiekvienas mokosi iš kito perspektyvos.' },
  '2-2': { score: 76, en: 'Two empaths who understand each other deeply — harmonious and loving, though both may need to push each other toward decisive action.', ru: 'Два эмпата, глубоко понимающие друг друга — гармоничный и любящий союз, хотя обоим может понадобиться побуждать друг друга к решительным действиям.', uk: 'Два емпати, що глибоко розуміють одне одного — гармонійний і люблячий союз, хоча обом може знадобитися спонукати одне одного до рішучих дій.', fr: 'Deux empathiques qui se comprennent profondément — une union harmonieuse et aimante, bien que les deux aient besoin de se pousser mutuellement vers l\'action.', lt: 'Du empatai, giliai suprantantys vienas kitą — harmoningas ir mylintis ryšys, nors abiem gali reikėti stumti vienas kitą ryžtingų veiksmų link.' },
  '2-3': { score: 74, en: 'The gentle 2 nurtures the expressive 3\'s creative gifts — a warm, emotionally rich partnership with genuine affection.', ru: 'Мягкая 2 питает творческие дары выразительной 3 — тёплое, эмоционально богатое партнёрство с искренней привязанностью.', uk: 'М\'яка 2 живить творчі дари виразної 3 — тепле, емоційно багате партнерство зі щирою прихильністю.', fr: 'Le doux 2 nourrit les dons créatifs de l\'expressif 3 — un partenariat chaleureux et émotionnellement riche avec une affection sincère.', lt: 'Švelnus 2 maitina išraiškingo 3 kūrybinius talentus — šiltas, emociškai turtingas partnerystė su nuoširdia meile.' },
  '2-4': { score: 82, en: 'Sensitivity meets stability in this beautifully balanced pairing — 2\'s warmth and 4\'s groundedness create a secure and loving home.', ru: 'Чувствительность встречает стабильность в этой прекрасно сбалансированной паре — теплота 2 и приземлённость 4 создают безопасный и любящий дом.', uk: 'Чутливість зустрічає стабільність у цій чудово збалансованій парі — теплота 2 та заземленість 4 створюють безпечний і люблячий дім.', fr: 'La sensibilité rencontre la stabilité dans ce duo parfaitement équilibré — la chaleur du 2 et l\'ancrage du 4 créent un foyer sûr et aimant.', lt: 'Jautrumas susitinka stabilumą šioje puikiai subalansuotoje poroje — 2 šilumas ir 4 žemiškumas sukuria saugius ir mylinčius namus.' },
  '2-5': { score: 55, en: 'The security-seeking 2 and freedom-loving 5 want fundamentally different things — commitment and open communication are essential to bridge this gap.', ru: 'Стремящаяся к безопасности 2 и любящая свободу 5 хотят принципиально разных вещей — обязательства и открытое общение необходимы для преодоления этого разрыва.', uk: 'Прагнуча безпеки 2 і люблача свободу 5 хочуть принципово різних речей — зобов\'язання та відкрите спілкування необхідні для подолання цієї прогалини.', fr: 'Le 2 en quête de sécurité et le 5 épris de liberté veulent des choses fondamentalement différentes — l\'engagement et la communication sont essentiels.', lt: 'Saugumo ieškantis 2 ir laisvės mylintis 5 nori iš esmės skirtingų dalykų — įsipareigojimas ir atviras bendravimas yra būtini šiai spragai užpildyti.' },
  '2-6': { score: 88, en: 'One of the most naturally compatible pairings — both are devoted to love, family and the care of others, creating deep, lasting harmony.', ru: 'Одна из наиболее естественно совместимых пар — оба преданы любви, семье и заботе о других, создавая глубокую, долговечную гармонию.', uk: 'Одна з найбільш природно сумісних пар — обидва віддані любові, сім\'ї та турботі про інших, створюючи глибоку, довготривалу гармонію.', fr: 'L\'une des paires les plus naturellement compatibles — tous deux dévoués à l\'amour, la famille et le soin des autres, créant une harmonie profonde et durable.', lt: 'Vienas iš natūraliausiai suderinamų porų — abu atsidavę meilei, šeimai ir kitų rūpinimuisi, sukuriantys gilią, ilgalaikę harmoniją.' },
  '2-7': { score: 74, en: 'The intuitive 2 and reflective 7 share a deep emotional and spiritual understanding that transcends words — quietly profound.', ru: 'Интуитивная 2 и рефлексирующая 7 разделяют глубокое эмоциональное и духовное понимание, выходящее за пределы слов — тихо глубокий союз.', uk: 'Інтуїтивна 2 і рефлексуюча 7 поділяють глибоке емоційне та духовне розуміння, що виходить за межі слів — тихо глибокий союз.', fr: 'L\'intuitif 2 et le réflexif 7 partagent une compréhension émotionnelle et spirituelle profonde qui transcende les mots — une union profondément silencieuse.', lt: 'Intuityvus 2 ir apmąstantis 7 dalijasi gilia emocine ir dvasine supratimu, peržengiančiu žodžius — tyliai gili sąjunga.' },
  '2-8': { score: 62, en: 'The gentle 2 may feel overlooked by the achievement-focused 8 — mutual respect and emotional acknowledgement are key to making this work.', ru: 'Мягкая 2 может чувствовать себя незамеченной ориентированной на достижения 8 — взаимное уважение и эмоциональное признание являются ключом к успеху.', uk: 'М\'яка 2 може відчувати себе непоміченою орієнтованою на досягнення 8 — взаємна повага та емоційне визнання є ключем до успіху.', fr: 'Le doux 2 peut se sentir négligé par le 8 axé sur les réalisations — le respect mutuel et la reconnaissance émotionnelle sont essentiels.', lt: 'Švelnus 2 gali jaustis nepastebėtas pasiekimais orientuoto 8 — abipusė pagarba ir emocinis pripažinimas yra raktas į sėkmę.' },
  '2-9': { score: 78, en: 'Both are givers by nature — the 2\'s personal devotion blends beautifully with the 9\'s universal compassion, creating a deeply caring bond.', ru: 'Оба по природе своей отдающие — личная преданность 2 прекрасно сочетается с универсальным состраданием 9, создавая глубоко заботливую связь.', uk: 'Обоє за природою свою — особиста відданість 2 чудово поєднується з універсальним співчуттям 9, створюючи глибоко дбайливий зв\'язок.', fr: 'Tous deux sont des donneurs par nature — la dévotion personnelle du 2 se marie magnifiquement à la compassion universelle du 9, créant un lien profondément attentionné.', lt: 'Abu yra davėjai iš prigimties — asmeninė 2 atsidavimas puikiai derinasi su universalia 9 užuojauta, sukuriant giliai rūpestingą ryšį.' },
  '3-3': { score: 68, en: 'Two creative souls spark joy and laughter together, but without structure this union can scatter its extraordinary potential.', ru: 'Две творческие души зажигают радость и смех вместе, но без структуры этот союз может растратить свой необыкновенный потенциал.', uk: 'Дві творчі душі запалюють радість і сміх разом, але без структури цей союз може розпорошити свій надзвичайний потенціал.', fr: 'Deux âmes créatives suscitent joie et rires, mais sans structure cette union peut disperser son extraordinaire potentiel.', lt: 'Dvi kūrybingos sielos kuria džiaugsmą ir juoką kartu, bet be struktūros šis ryšys gali išsklaidyti savo nepaprastą potencialą.' },
  '3-4': { score: 55, en: 'Creative spontaneity meets disciplined structure — friction is likely, but this pairing can produce remarkable results if both honour what the other brings.', ru: 'Творческая спонтанность встречает дисциплинированную структуру — трения вероятны, но эта пара может достичь замечательных результатов, если оба чтят то, что приносит другой.', uk: 'Творча спонтанність зустрічає дисципліновану структуру — тертя ймовірні, але ця пара може досягти чудових результатів, якщо обидва шанують те, що приносить інший.', fr: 'La spontanéité créative rencontre la structure disciplinée — des frictions sont probables, mais ce duo peut produire des résultats remarquables si chacun honore l\'apport de l\'autre.', lt: 'Kūrybinis spontaniškumas susitinka su disciplinuota struktūra — trintis tikėtina, bet ši pora gali pasiekti puikių rezultatų, jei abu gerbia tai, ką kitas atsineša.' },
  '3-5': { score: 86, en: 'Pure excitement — both love adventure, variety and living in the moment, making this one of the most naturally vibrant pairings.', ru: 'Чистый восторг — оба любят приключения, разнообразие и жизнь в настоящем моменте, что делает эту пару одной из наиболее естественно живых.', uk: 'Чистий захват — обоє люблять пригоди, різноманітність та життя в теперішньому моменті, що робить цю пару однією з найбільш природно живих.', fr: 'Pure excitation — tous deux aiment l\'aventure, la variété et vivre le moment présent, faisant de ce duo l\'un des plus naturellement vibrants.', lt: 'Gryna jaudinimasis — abu mėgsta nuotykius, įvairovę ir gyvenimą dabartimi, todėl ši pora yra viena iš natūraliausiai gyvybingų.' },
  '3-6': { score: 78, en: 'The creative 3 and nurturing 6 make a warm and joyful home — 6 provides the loving structure that allows 3\'s expression to flourish.', ru: 'Творческая 3 и заботливая 6 создают тёплый и радостный дом — 6 обеспечивает любящую структуру, позволяющую расцвести самовыражению 3.', uk: 'Творча 3 і дбайлива 6 створюють тепле і радісне домашнє середовище — 6 забезпечує люблячу структуру, що дозволяє процвітати самовираженню 3.', fr: 'Le créatif 3 et le protecteur 6 créent un foyer chaleureux et joyeux — le 6 offre la structure aimante qui permet à l\'expression du 3 de s\'épanouir.', lt: 'Kūrybingas 3 ir rūpestingas 6 sukuria šiltus ir džiaugsmingus namus — 6 suteikia mylinčią struktūrą, leidžiančią 3 raiškai klestėti.' },
  '3-7': { score: 62, en: 'The outgoing 3 and introspective 7 speak quite different social languages — this pairing works best when both create space for the other\'s opposite nature.', ru: 'Общительная 3 и интроспективная 7 говорят на разных социальных языках — эта пара лучше всего работает, когда оба создают пространство для противоположной природы другого.', uk: 'Товариська 3 і інтроспективна 7 говорять різними соціальними мовами — ця пара найкраще працює, коли обидва створюють простір для протилежної природи іншого.', fr: 'L\'extraverti 3 et l\'introspectif 7 parlent des langages sociaux très différents — ce duo fonctionne mieux quand chacun fait de la place pour la nature opposée de l\'autre.', lt: 'Socialus 3 ir introspektyvus 7 kalba gana skirtingomis socialinėmis kalbomis — ši pora geriausiai veikia, kai abu sukuria erdvę kito priešingai prigimčiai.' },
  '3-8': { score: 65, en: 'Creative vision meets material ambition — there is real potential here but both must respect the other\'s priorities and different definitions of success.', ru: 'Творческое видение встречается с материальными амбициями — здесь есть реальный потенциал, но оба должны уважать приоритеты другого и разные определения успеха.', uk: 'Творче бачення зустрічається з матеріальними амбіціями — тут є реальний потенціал, але обидва повинні поважати пріоритети іншого та різні визначення успіху.', fr: 'La vision créative rencontre l\'ambition matérielle — il y a un vrai potentiel ici, mais les deux doivent respecter les priorités et les définitions différentes du succès.', lt: 'Kūrybinė vizija susitinka su materialine ambicija — čia yra tikras potencialas, bet abu turi gerbti kito prioritetus ir skirtingas sėkmės apibrėžtis.' },
  '3-9': { score: 82, en: 'A beautifully inspired pairing — both are creative, expressive and visionary, sharing a natural joy that uplifts everyone around them.', ru: 'Прекрасно вдохновлённая пара — оба творческие, выразительные и провидческие, разделяющие естественную радость, которая поднимает всех вокруг.', uk: 'Прекрасно натхнена пара — обидва творчі, виразні та провидницькі, ділячи природну радість, яка піднімає всіх навколо.', fr: 'Un duo magnifiquement inspiré — tous deux créatifs, expressifs et visionnaires, partageant une joie naturelle qui élève tous ceux qui les entourent.', lt: 'Puikiai įkvėpta pora — abu kūrybingi, išraiškingi ir visionieriai, dalijantys natūralų džiaugsmą, kuris pakelia visus aplinkinius.' },
  '4-4': { score: 80, en: 'Rock solid and deeply reliable — two builders who share values of hard work, loyalty and long-term commitment, creating something truly lasting.', ru: 'Прочный и надёжный союз — два строителя, разделяющих ценности трудолюбия, верности и долгосрочных обязательств, создающих нечто поистине долговечное.', uk: 'Міцний і надійний союз — два будівельники, що поділяють цінності наполегливої праці, вірності та довгострокових зобов\'язань, створюючи щось справді довговічне.', fr: 'Solide comme le roc et très fiable — deux bâtisseurs partageant des valeurs de travail acharné, de loyauté et d\'engagement à long terme, créant quelque chose de vraiment durable.', lt: 'Tvirtas kaip uola ir itin patikimas — du statybininkai, dalijantys sunkaus darbo, ištikimybės ir ilgalaikio įsipareigojimo vertybes, sukuriantys kažką tikrai ilgalaikio.' },
  '4-5': { score: 48, en: 'One wants routine and security, the other craves novelty and freedom — this is one of the most challenging pairings and requires enormous mutual effort.', ru: 'Один хочет рутины и безопасности, другой жаждет новизны и свободы — это одна из наиболее сложных пар, требующая огромных взаимных усилий.', uk: 'Один хоче рутини та безпеки, інший прагне новизни та свободи — це одна з найбільш складних пар і вимагає величезних взаємних зусиль.', fr: 'L\'un veut routine et sécurité, l\'autre aspire à la nouveauté et à la liberté — c\'est l\'une des paires les plus difficiles et nécessite un effort mutuel énorme.', lt: 'Vienas nori rutinos ir saugumo, kitas trokšta naujovių ir laisvės — tai viena iš sudėtingiausių porų ir reikalauja milžiniškų abipusių pastangų.' },
  '4-6': { score: 78, en: 'Practical dedication meets heartfelt nurturing — both are devoted to creating a secure, loving life and complement each other beautifully.', ru: 'Практическая преданность встречает сердечную заботу — оба преданы созданию безопасной, любящей жизни и прекрасно дополняют друг друга.', uk: 'Практична відданість зустрічає щиру турботу — обидва віддані створенню безпечного, люблячого життя і чудово доповнюють одне одного.', fr: 'Le dévouement pratique rencontre l\'attention sincère — tous deux sont dévoués à créer une vie sûre et aimante et se complètent magnifiquement.', lt: 'Praktinis atsidavimas susitinka su nuoširdia rūpyba — abu atsidavę kuriant saugų, mylintį gyvenimą ir puikiai papildo vienas kitą.' },
  '4-7': { score: 66, en: 'The practical 4 and philosophical 7 occupy different inner worlds but can grow profoundly through their differences if they maintain deep respect.', ru: 'Практичная 4 и философская 7 занимают разные внутренние миры, но могут глубоко расти через свои различия, если сохраняют глубокое уважение.', uk: 'Практична 4 і філософська 7 займають різні внутрішні світи, але можуть глибоко зростати завдяки своїм відмінностям, якщо зберігають глибоку повагу.', fr: 'Le pratique 4 et le philosophe 7 habitent des mondes intérieurs différents mais peuvent grandir profondément à travers leurs différences avec un respect profond.', lt: 'Praktiškas 4 ir filosofinis 7 gyvena skirtinguose vidiniuose pasauliuose, bet gali giliai augti per savo skirtumus, jei palaiko gilią pagarbą.' },
  '4-8': { score: 86, en: 'A powerhouse combination for achievement — both are determined builders and together they can construct impressive, lasting success in any domain.', ru: 'Мощная комбинация для достижений — оба решительные строители, и вместе они могут построить впечатляющий, долговечный успех в любой области.', uk: 'Потужна комбінація для досягнень — обидва рішучі будівельники, і разом вони можуть побудувати вражаючий, довговічний успіх у будь-якій сфері.', fr: 'Une combinaison puissante pour la réussite — tous deux sont des bâtisseurs déterminés et ensemble ils peuvent construire un succès impressionnant et durable dans n\'importe quel domaine.', lt: 'Galinga pasiekimų kombinacija — abu yra ryžtingi statybininkai ir kartu jie gali sukurti įspūdingą, ilgalaikę sėkmę bet kurioje srityje.' },
  '4-9': { score: 62, en: 'The grounded 4 and idealistic 9 may struggle to align on practical versus universal priorities — shared values and honest dialogue are the bridge.', ru: 'Приземлённая 4 и идеалистическая 9 могут испытывать трудности с согласованием практических и универсальных приоритетов — общие ценности и честный диалог являются мостом.', uk: 'Заземлена 4 і ідеалістична 9 можуть мати труднощі з узгодженням практичних і універсальних пріоритетів — спільні цінності та чесний діалог є мостом.', fr: 'Le 4 terre-à-terre et l\'idéaliste 9 peuvent avoir du mal à s\'aligner sur les priorités pratiques versus universelles — des valeurs partagées et un dialogue honnête sont le pont.', lt: 'Žemiškas 4 ir idealistinis 9 gali sunkiai suderinti praktines ir universalias prioritetus — bendros vertybės ir sąžiningas dialogas yra tiltas.' },
  '5-5': { score: 70, en: 'Adventurous, exciting and never boring — this pairing thrives on shared freedom but must eventually anchor somewhere to avoid endless drifting.', ru: 'Приключенческий, захватывающий и никогда не скучный — эта пара процветает на общей свободе, но в конечном счёте должна где-то заякориться, чтобы избежать бесконечного дрейфа.', uk: 'Пригодницький, захоплюючий і ніколи не нудний — ця пара процвітає на спільній свободі, але зрештою повинна десь закріпитися, щоб уникнути нескінченного дрейфу.', fr: 'Aventureux, excitant et jamais ennuyeux — ce duo prospère sur la liberté partagée mais doit finalement s\'ancrer quelque part pour éviter une dérive sans fin.', lt: 'Nuotykingas, jaudinantis ir niekada nuobodus — ši pora klesti bendros laisvės dėka, bet galiausiai turi kažkur inkaruoti, kad išvengtų begalinio dreifavimo.' },
  '5-6': { score: 58, en: 'Freedom-seeking 5 and commitment-oriented 6 pull in opposite directions — love can be deep here but requires significant compromise and trust.', ru: 'Стремящаяся к свободе 5 и ориентированная на обязательства 6 тянут в противоположные стороны — любовь может быть глубокой, но требует значительных компромиссов и доверия.', uk: 'Прагнуча свободи 5 і орієнтована на зобов\'язання 6 тягнуть у протилежні боки — любов може бути глибокою, але вимагає значних компромісів і довіри.', fr: 'Le 5 en quête de liberté et le 6 axé sur l\'engagement tirent dans des directions opposées — l\'amour peut être profond ici mais nécessite des compromis significatifs et de la confiance.', lt: 'Laisvės ieškantis 5 ir įsipareigojimams orientuotas 6 traukia priešingomis kryptimis — meilė čia gali būti gili, bet reikalauja reikšmingų kompromisų ir pasitikėjimo.' },
  '5-7': { score: 76, en: 'Both are independent, curious and deeply interested in the meaning beneath the surface — they explore the world together with ease and mutual respect.', ru: 'Оба независимы, любопытны и глубоко интересуются смыслом под поверхностью — они исследуют мир вместе с лёгкостью и взаимным уважением.', uk: 'Обоє незалежні, допитливі та глибоко зацікавлені у сенсі під поверхнею — вони досліджують світ разом із легкістю та взаємною повагою.', fr: 'Tous deux indépendants, curieux et profondément intéressés par le sens sous la surface — ils explorent le monde ensemble avec aisance et respect mutuel.', lt: 'Abu yra nepriklausomi, smalsūs ir giliai suinteresuoti prasme po paviršiumi — jie tyrinėja pasaulį kartu su lengvumu ir abipuse pagarba.' },
  '5-8': { score: 72, en: 'High energy and driven — this is a vibrant and stimulating match, though 8\'s need for direction may occasionally clash with 5\'s impulse toward freedom.', ru: 'Высокая энергия и целеустремлённость — это живая и стимулирующая пара, хотя потребность 8 в направлении может иногда конфликтовать с импульсом 5 к свободе.', uk: 'Висока енергія та цілеспрямованість — це жива і стимулююча пара, хоча потреба 8 в напрямку може іноді конфліктувати з імпульсом 5 до свободи.', fr: 'Haute énergie et motivation — un duo vibrant et stimulant, bien que le besoin de direction du 8 puisse parfois entrer en conflit avec l\'impulsion vers la liberté du 5.', lt: 'Aukšta energija ir ryžtingumas — tai gyvybinga ir skatinanti pora, nors 8 poreikis krypties gali kartais konfliktuoti su 5 impulsu laisvei.' },
  '5-9': { score: 76, en: 'Both share a love of experience, wisdom and a broad worldview — they journey through life with a sense of shared adventure and philosophical depth.', ru: 'Оба разделяют любовь к опыту, мудрости и широкому мировоззрению — они путешествуют по жизни с ощущением общего приключения и философской глубины.', uk: 'Обоє поділяють любов до досвіду, мудрості та широкого світогляду — вони подорожують по житті з відчуттям спільної пригоди та філософської глибини.', fr: 'Tous deux partagent un amour de l\'expérience, de la sagesse et d\'une vision large du monde — ils voyagent à travers la vie avec un sens de l\'aventure partagée et de la profondeur philosophique.', lt: 'Abu dalijasi meile patirčiai, išminčiai ir plačiam pasaulėžiūrai — jie keliauja per gyvenimą su bendros nuotykio ir filosofinio gylio jausmu.' },
  '6-6': { score: 84, en: 'Deeply harmonious and devoted — two nurturers create a home filled with warmth, beauty and unconditional love that sustains both of them.', ru: 'Глубоко гармоничный и преданный союз — два заботливых человека создают дом, наполненный теплом, красотой и безусловной любовью, которая поддерживает обоих.', uk: 'Глибоко гармонійний та відданий союз — два дбайливих створюють дім, наповнений теплом, красою та безумовною любов\'ю, яка підтримує обох.', fr: 'Profondément harmonieux et dévoués — deux protecteurs créent un foyer rempli de chaleur, de beauté et d\'amour inconditionnel qui les soutient tous les deux.', lt: 'Giliai harmoningas ir atsidavęs — du rūpestingi žmonės sukuria namus, pilnus šilumos, grožio ir besąlygiškos meilės, kuri palaiko abu.' },
  '6-7': { score: 66, en: 'The home-loving 6 and solitude-seeking 7 need different things from closeness, but a profound spiritual and emotional connection can develop with patience.', ru: 'Любящая дом 6 и ищущая уединения 7 нуждаются в разных вещах от близости, но глубокая духовная и эмоциональная связь может развиться при терпении.', uk: 'Люблача дім 6 і ищуча самотності 7 потребують різних речей від близькості, але глибокий духовний та емоційний зв\'язок може розвинутися при терпінні.', fr: 'Le 6 attaché au foyer et le 7 en quête de solitude ont besoin de choses différentes de la proximité, mais une connexion profonde peut se développer avec patience.', lt: 'Namus mylintis 6 ir vienatvės ieškantis 7 nori skirtingų dalykų iš artimumo, bet gilus dvasinis ir emocinis ryšys gali atsivystyti su kantrybe.' },
  '6-8': { score: 72, en: 'Love of family and love of achievement can combine beautifully here — 8 provides material security while 6 creates the warm home 8 quietly craves.', ru: 'Любовь к семье и любовь к достижениям могут прекрасно сочетаться здесь — 8 обеспечивает материальную безопасность, пока 6 создаёт тёплый дом, которого тихо желает 8.', uk: 'Любов до сім\'ї та любов до досягнень можуть прекрасно поєднуватися тут — 8 забезпечує матеріальну безпеку, поки 6 створює теплий дім, якого тихо прагне 8.', fr: 'L\'amour de la famille et l\'amour de la réussite peuvent se combiner magnifiquement ici — le 8 assure la sécurité matérielle tandis que le 6 crée le foyer chaleureux dont le 8 a besoin.', lt: 'Šeimos meilė ir pasiekimų meilė čia gali puikiai derinti — 8 suteikia materialinį saugumą, o 6 sukuria šiltus namus, kurių 8 tyliai trokšta.' },
  '6-9': { score: 86, en: 'Two hearts devoted to others — the 6\'s personal love and the 9\'s universal compassion create a deeply generous, warm and purposeful partnership.', ru: 'Два сердца, преданных другим — личная любовь 6 и универсальное сострадание 9 создают глубоко щедрое, тёплое и целенаправленное партнёрство.', uk: 'Два серця, віддані іншим — особиста любов 6 та універсальне співчуття 9 створюють глибоко щедре, тепле та цілеспрямоване партнерство.', fr: 'Deux cœurs dévoués aux autres — l\'amour personnel du 6 et la compassion universelle du 9 créent un partenariat profondément généreux, chaleureux et plein de sens.', lt: 'Dvi širdys, atsidavusios kitiems — asmeninė 6 meilė ir universali 9 užuojauta sukuria giliai dosnią, šiltą ir tikslingą partnerystę.' },
  '7-7': { score: 76, en: 'A rare meeting of two deeply introspective souls — they understand each other on levels others never could, creating a bond of profound depth and silence.', ru: 'Редкая встреча двух глубоко интроспективных душ — они понимают друг друга на уровнях, которые другие никогда не смогут, создавая связь глубины и тишины.', uk: 'Рідкісна зустріч двох глибоко інтроспективних душ — вони розуміють одне одного на рівнях, яких інші ніколи не зможуть, створюючи зв\'язок глибини та тиші.', fr: 'Une rare rencontre de deux âmes profondément introspectives — ils se comprennent à des niveaux que les autres ne pourraient jamais atteindre, créant un lien de profondeur et de silence.', lt: 'Retas dviejų giliai introspektyvių sielų susitikimas — jie supranta vienas kitą lygiais, kurių kiti niekada negalėtų, kurdami gilaus gylio ir tylos ryšį.' },
  '7-8': { score: 56, en: 'The spiritual 7 and material 8 see the world through fundamentally different lenses — genuine respect for each other\'s path is the only foundation that works here.', ru: 'Духовная 7 и материальная 8 видят мир через принципиально разные линзы — искреннее уважение к пути друг друга — единственная основа, которая работает здесь.', uk: 'Духовна 7 і матеріальна 8 бачать світ через принципово різні лінзи — щира повага до шляху одне одного — єдина основа, яка тут працює.', fr: 'Le 7 spirituel et le 8 matériel voient le monde à travers des objectifs fondamentalement différents — un respect sincère pour le chemin de l\'autre est la seule base qui fonctionne ici.', lt: 'Dvasinis 7 ir materialinis 8 mato pasaulį per iš esmės skirtingas prizmės — tikras abipusis pagarbas vienas kito keliui yra vienintelis čia veikiantis pagrindas.' },
  '7-9': { score: 82, en: 'Philosophical, wise and deeply connected — both seek meaning, truth and a deeper understanding of life, creating a quietly profound and enriching partnership.', ru: 'Философский, мудрый и глубоко связанный союз — оба ищут смысл, истину и более глубокое понимание жизни, создавая тихо глубокое и обогащающее партнёрство.', uk: 'Філософський, мудрий та глибоко пов\'язаний союз — обидва шукають сенс, істину та глибше розуміння життя, створюючи тихо глибоке та збагачуюче партнерство.', fr: 'Philosophique, sage et profondément connecté — tous deux cherchent le sens, la vérité et une compréhension plus profonde de la vie, créant un partenariat profondément enrichissant.', lt: 'Filosofiškas, išmingas ir giliai susietas — abu ieško prasmės, tiesos ir gilesnio gyvenimo supratimo, kurdami tyliai gilią ir praturtinančią partnerystę.' },
  '8-8': { score: 66, en: 'Powerful and ambitious — this pairing has enormous potential but must overcome the tendency to compete rather than collaborate for true shared success.', ru: 'Мощный и амбициозный союз — эта пара имеет огромный потенциал, но должна преодолеть тенденцию к конкуренции, а не сотрудничеству для истинного совместного успеха.', uk: 'Потужний та амбітний союз — ця пара має величезний потенціал, але повинна подолати тенденцію до конкуренції, а не співпраці для справжнього спільного успіху.', fr: 'Puissant et ambitieux — ce duo a un énorme potentiel mais doit surmonter la tendance à la compétition plutôt qu\'à la collaboration pour une vraie réussite partagée.', lt: 'Galingas ir ambicingas — ši pora turi milžinišką potencialą, bet turi įveikti polinkį konkuruoti, o ne bendradarbiauti tikrai bendrai sėkmei pasiekti.' },
  '8-9': { score: 62, en: 'The achievement-focused 8 and selfless 9 have different motivations — when 8 develops generosity and 9 respects material realities, this pairing can be genuinely complementary.', ru: 'Ориентированная на достижения 8 и бескорыстная 9 имеют разные мотивации — когда 8 развивает щедрость, а 9 уважает материальные реалии, эта пара может быть подлинно взаимодополняющей.', uk: 'Орієнтована на досягнення 8 і безкорислива 9 мають різні мотивації — коли 8 розвиває щедрість, а 9 поважає матеріальні реалії, ця пара може бути справді взаємодоповнюючою.', fr: 'Le 8 axé sur les réalisations et le 9 altruiste ont des motivations différentes — quand le 8 développe la générosité et le 9 respecte les réalités matérielles, ce duo peut être vraiment complémentaire.', lt: 'Pasiekimais orientuotas 8 ir nesavanaudiškas 9 turi skirtingas motyvacijas — kai 8 ugdo dosnumą, o 9 gerbia materialines realijas, ši pora gali būti tikrai papildanti.' },
  '9-9': { score: 82, en: 'Two humanitarians united by shared vision and compassion — deeply inspiring together, they can accomplish meaningful things that benefit far beyond themselves.', ru: 'Два гуманиста, объединённых общим видением и состраданием — глубоко вдохновляющие вместе, они могут достичь значимых вещей, которые принесут пользу далеко за пределами их самих.', uk: 'Два гуманісти, об\'єднані спільним баченням та співчуттям — глибоко надихаючі разом, вони можуть досягти значущих речей, що принесуть користь далеко за їхніми межами.', fr: 'Deux humanitaires unis par une vision partagée et la compassion — profondément inspirants ensemble, ils peuvent accomplir des choses significatives qui profitent bien au-delà d\'eux-mêmes.', lt: 'Du humanistai, suvienyti bendros vizijos ir užuojautos — giliai įkveipiantys kartu, jie gali pasiekti reikšmingų dalykų, naudingų toli už jų pačių ribų.' },
};

function digitSum(n: number): number {
  return String(Math.abs(n)).split('').reduce((s, d) => s + parseInt(d, 10), 0);
}

function reduce(n: number): number {
  if (n === 11 || n === 22) return n;
  if (n <= 9) return n;
  return reduce(digitSum(n));
}

function calcLifePath(dateStr: string): number {
  const [yyyy, mm, dd] = dateStr.split('-');
  const total = (dd + mm + yyyy).split('').reduce((s, d) => s + parseInt(d, 10), 0);
  return reduce(total);
}

function compatKey(a: number, b: number): string {
  const baseA = a === 11 ? 2 : a === 22 ? 4 : a;
  const baseB = b === 11 ? 2 : b === 22 ? 4 : b;
  return `${Math.min(baseA, baseB)}-${Math.max(baseA, baseB)}`;
}

function getLevel(score: number, t: typeof T['en']): string {
  if (score >= 80) return t.levels.excellent;
  if (score >= 65) return t.levels.good;
  if (score >= 50) return t.levels.moderate;
  return t.levels.challenging;
}

function scoreToHearts(score: number): string {
  const filled = Math.round(score / 10);
  return '❤️'.repeat(filled) + '🤍'.repeat(10 - filled);
}

export default function NumerologyCompatibilityCalculator({ locale }: Props) {
  const t = T[locale] ?? T.en;
  const [date1, setDate1] = useState('');
  const [date2, setDate2] = useState('');
  const [result, setResult] = useState<{ lp1: number; lp2: number; entry: CompatEntry } | null>(null);
  const [error, setError] = useState('');

  const calculate = () => {
    if (!date1 || !date2) { setError(t.errEmpty); setResult(null); return; }
    const d1 = new Date(date1), d2 = new Date(date2);
    if (isNaN(d1.getTime()) || isNaN(d2.getTime())) { setError(t.errInvalid); setResult(null); return; }
    const lp1 = calcLifePath(date1);
    const lp2 = calcLifePath(date2);
    const key = compatKey(lp1, lp2);
    const entry = COMPAT[key];
    if (!entry) { setError(t.errInvalid); setResult(null); return; }
    setError('');
    setResult({ lp1, lp2, entry });
  };

  const desc = result ? ((result.entry[locale as keyof CompatEntry] as string | undefined) ?? result.entry.en) : '';

  return (
    <div className={styles.calc}>
      <div className={styles.calc__fields}>
        <div className={styles.calc__field}>
          <label className={styles.calc__label}>{t.label1}</label>
          <input type="date" className={styles.calc__input} value={date1} max={new Date().toISOString().split('T')[0]} onChange={(e) => { setDate1(e.target.value); setError(''); setResult(null); }} />
        </div>
        <div className={styles.calc__field}>
          <label className={styles.calc__label}>{t.label2}</label>
          <input type="date" className={styles.calc__input} value={date2} max={new Date().toISOString().split('T')[0]} onChange={(e) => { setDate2(e.target.value); setError(''); setResult(null); }} />
        </div>
      </div>
      <button className={styles.calc__btn} onClick={calculate}>{t.btn}</button>
      {error && <p className={styles.calc__error}>{error}</p>}
      {result && (
        <div className={styles.calc__result}>
          <div className={styles.calc__paths}>
            <span className={styles.calc__path_num}>{result.lp1}</span>
            <span className={styles.calc__path_sep}>♥</span>
            <span className={styles.calc__path_num}>{result.lp2}</span>
          </div>
          <div className={styles.calc__score}>{scoreToHearts(result.entry.score)}</div>
          <div className={styles.calc__level}>{getLevel(result.entry.score, t)} — {result.entry.score}%</div>
          <p className={styles.calc__desc}>{desc}</p>
        </div>
      )}
    </div>
  );
}
